    
dist: trusty
sudo: required
language: python
python:
  - "3.6"

before_install:
- sudo apt-get -qq update
- sudo apt-get install -qq cmake python-numpy python-scipy libboost-python-dev
- pip install git+https://github.com/ageitgey/face_recognition_models

install:
  - pip install -r requirements.txt
  #- pip install tox-travis

#script: tox

# Temporary for Python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

#deploy:
#  provider: heroku
#  api_key:
#    secure: "$HEROKU_API_KEY"
#  on:
#    tags: true
#    repo: gps20191/api-reconhecimento
#    branches:    
#      only:      
#        - master
#  app:
#    develop: api-reconhecimento-gps
